package dev.supachain.robot.messenger

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Defines the Roles in an AI Conversation
 *
 * This enumeration represents the different roles that entities can play within an AI-powered conversation. Each role
 * has a specific purpose and helps to distinguish between the various types of messages exchanged.
 *
 * The available roles are:
 *
 * - `SYSTEM`:  Typically used for initial instructions or messages that set the context for the conversation. These
 * messages are often not seen directly by the user.
 * - `USER`: Represents messages sent by the human user interacting with the AI.
 * - `ASSISTANT`: Represents messages generated by the AI model in response to user queries or as part of the
 *    conversation flow.
 * - `FUNCTION`:  Indicates messages generated by tools or functions used by the AI to perform specific tasks (e.g.,
 *    calculations, data retrieval).
 *
 * Example Usage:
 *
 * ```kotlin
 * val userMessage = Message(Role.USER, "What's the weather like today?")
 * val assistantResponse = Message(Role.ASSISTANT, "It's sunny and 25 degrees Celsius.")
 * ```
 *
 * Why Roles are Important:
 *
 * - **Contextual Understanding:** Roles help the AI model understand the context of each message, allowing it to tailor its responses more effectively.
 * - **Conversation Flow:** Clearly defined roles enable structured conversations and facilitate the integration of tools within the AI workflow.
 * - **Debugging and Analysis:**  Roles make it easier to track the flow of messages and identify potential issues during development and analysis.
 *
 * Note:  The specific roles used might vary depending on the AI application's requirements. This library provides
 * these standard roles to cover common use cases.
 *
 * @since 0.1.0-alpha

 */
@Suppress("unused")
@Serializable
enum class Role {
    @SerialName("system")
    SYSTEM,

    @SerialName("user")
    USER,

    @SerialName("assistant")
    ASSISTANT,

    @SerialName("function")
    FUNCTION
}