package dev.supachain.robot.messenger.messaging

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents token usage statistics for an AI provider interaction.
 *
 * This class encapsulates details about the number of tokens processed during a request to
 * an AI provider, including:
 *
 * - `promptTokens`: The number of tokens present in the input prompt or request sent to the provider.
 * - `completionTokens`: The number of tokens generated by the AI provider in its response.
 * - `totalTokens`: The total number of tokens processed, calculated as the sum of `promptTokens` and `completionTokens`.
 *
 * Token usage is a critical factor in understanding the cost and efficiency of interactions with AI providers,
 * especially those that charge based on token usage. This class helps you monitor and optimize your application's
 * interactions with the AI provider.
 *
 * @since 0.1.0

 */
@Serializable
data class Usage(
    @SerialName("prompt_tokens") val promptTokens: Int,
    @SerialName("completion_tokens") val completionTokens: Int,
    @SerialName("total_tokens") val totalTokens: Int
)

@Suppress("unused")
@Serializable
data class EmbedResponse(val model: String)

@Suppress("unused")
@Serializable
data class ModResponse(val model: String)

@Suppress("unused")
@Serializable
data class AudioResponse(val model: String)

@Suppress("unused")
@Serializable
data class ImageResponse(val model: String)

@Serializable
data class ToolCall(val id: String, val type: String, val function: FunctionCall)

@Serializable
data class FunctionCall(val arguments: String, val name: String)

@Serializable
data class CommonLogProbContainer(val content: CommonLogProbabilities)

@Serializable
data class CommonLogProbabilities(
    val token: String,
    @SerialName("logprob")
    val logProb: Double,
    val bytes: List<Byte>,
    @SerialName("top_logprobs")
    val topLogProbabilities: List<CommonLogProbabilities>? = null
)

// Error Handling
data class ErrorResponse(val error: ErrorDetails)

@Serializable
data class ErrorDetails(val message: String, val type: String, val param: String?, val code: String?)